"""initial tables

Revision ID: 4b93b7f76cf7
Revises: 
Create Date: 2025-10-08 18:48:09.951766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b93b7f76cf7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('venue', sa.String(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shows_id'), 'shows', ['id'], unique=False)
    op.create_index(op.f('ix_shows_starts_at'), 'shows', ['starts_at'], unique=False)
    op.create_index(op.f('ix_shows_title'), 'shows', ['title'], unique=False)
    op.create_index(op.f('ix_shows_venue'), 'shows', ['venue'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.String(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seats_id'), 'seats', ['id'], unique=False)
    op.create_index(op.f('ix_seats_seat_number'), 'seats', ['seat_number'], unique=False)
    op.create_index('unique_label_per_show', 'seats', ['show_id', 'seat_number'], unique=True)
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), server_default='HELD', nullable=False),
    sa.Column('hold_expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('HELD', 'CONFIRMED', 'EXPIRED')", name='reservation_status_check'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_id'), 'reservations', ['id'], unique=False)
    op.create_index(op.f('ix_reservations_seat_id'), 'reservations', ['seat_id'], unique=False)
    op.create_index(op.f('ix_reservations_user_id'), 'reservations', ['user_id'], unique=False)
    op.create_index('unique_active_reservation_per_seat', 'reservations', ['seat_id'], unique=True, postgresql_where=sa.text("status IN ('HELD', 'CONFIRMED')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_active_reservation_per_seat', table_name='reservations', postgresql_where=sa.text("status IN ('HELD', 'CONFIRMED')"))
    op.drop_index(op.f('ix_reservations_user_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_seat_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index('unique_label_per_show', table_name='seats')
    op.drop_index(op.f('ix_seats_seat_number'), table_name='seats')
    op.drop_index(op.f('ix_seats_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shows_venue'), table_name='shows')
    op.drop_index(op.f('ix_shows_title'), table_name='shows')
    op.drop_index(op.f('ix_shows_starts_at'), table_name='shows')
    op.drop_index(op.f('ix_shows_id'), table_name='shows')
    op.drop_table('shows')
    # ### end Alembic commands ###
